CREATE TABLE `client` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rdbIndex` varchar(64),
	`status` enum('active','hold') NOT NULL DEFAULT 'active',
	`name` varchar(255),
	`manager` varchar(100),
	`grade` varchar(50),
	`category` varchar(100),
	`mobile` varchar(50),
	`homePhone` varchar(50),
	`companyPhone` varchar(50),
	`fax` varchar(50),
	`otherPhone` varchar(50),
	`budget` varchar(100),
	`wantIndustry` varchar(255),
	`wantArea` varchar(255),
	`wantFeature` text,
	`wantType` varchar(100),
	`depositMin` decimal(15,4),
	`depositMax` decimal(15,4),
	`premiumMin` decimal(15,4),
	`premiumMax` decimal(15,4),
	`monthlyMin` decimal(15,4),
	`monthlyMax` decimal(15,4),
	`memo` text,
	`note1` text,
	`note2` text,
	`receivedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kwonri` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rdbIndex` varchar(64),
	`status` enum('active','hold') NOT NULL DEFAULT 'active',
	`name` varchar(255),
	`address` varchar(500),
	`location` varchar(255),
	`type` varchar(100),
	`industry` varchar(255),
	`manager` varchar(100),
	`grade` varchar(50),
	`category` varchar(100),
	`phone1` varchar(50),
	`phone2` varchar(50),
	`homePhone` varchar(50),
	`mobile` varchar(50),
	`ownerName` varchar(100),
	`rentArea` varchar(50),
	`realArea` varchar(50),
	`landArea` varchar(50),
	`floors` varchar(50),
	`deposit` decimal(15,4),
	`premium` decimal(15,4),
	`total` decimal(15,4),
	`monthlyRent` decimal(15,4),
	`manageFee` decimal(15,4),
	`vat` varchar(50),
	`memo1` text,
	`memo2` text,
	`memo3` text,
	`memo0` text,
	`memoEtc` text,
	`specialFeature` text,
	`recommendIndustry` varchar(255),
	`saleInfo` text,
	`receivedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kwonri_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kwonri_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`kwonriId` int NOT NULL,
	`date` timestamp,
	`deposit` decimal(15,4),
	`premium` decimal(15,4),
	`total` decimal(15,4),
	`note` text,
	`manager` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `kwonri_history_id` PRIMARY KEY(`id`)
);
